//! Builds vendor/nes_ntsc-0.2.2 natively when it has been fetched
//! (tools/fetch-oracle.sh); without it the crate compiles with the FFI
//! absent and the golden tests SKIP by name (REQUIRE_ORACLE=1 makes that
//! a failure, the house pattern for non-redistributed reference data).
//!
//! The library is configured by editing its nes_ntsc_config.h, so the
//! sources are copied to OUT_DIR beside a generated config: emphasis on
//! (512-entry palette), 32-bit output, u16 input. Quoted includes bind to
//! the including file's directory, which is why copying beats -I games.

use std::path::Path;

fn main() {
    println!("cargo::rustc-check-cfg=cfg(has_oracle)");
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let vendor = Path::new(&manifest).join("vendor/nes_ntsc-0.2.2");
    println!("cargo:rerun-if-changed={}", vendor.display());
    if !vendor.join("nes_ntsc.c").exists() {
        return;
    }

    let out = std::env::var("OUT_DIR").unwrap();
    let out = Path::new(&out);
    for f in ["nes_ntsc.c", "nes_ntsc.h", "nes_ntsc_impl.h"] {
        std::fs::copy(vendor.join(f), out.join(f)).unwrap();
    }
    std::fs::write(
        out.join("nes_ntsc_config.h"),
        "/* generated by ntsc-oracle build.rs: the recorded oracle configuration */\n\
         #ifndef NES_NTSC_CONFIG_H\n\
         #define NES_NTSC_CONFIG_H\n\
         #define NES_NTSC_EMPHASIS 1\n\
         #define NES_NTSC_OUT_DEPTH 32\n\
         #define NES_NTSC_IN_T unsigned short\n\
         #define NES_NTSC_ADJ_IN( in ) in\n\
         #endif\n",
    )
    .unwrap();
    cc::Build::new()
        .file(out.join("nes_ntsc.c"))
        .include(out)
        .opt_level(2)
        .warnings(false)
        .compile("nes_ntsc");
    println!("cargo::rustc-cfg=has_oracle");
}
