//! Reads data/nes-levels.toml (the gated transcription) and emits the level
//! constants as Rust. The table is never hand-typed into code (handoff spec
//! principle 4); this generator is the one place the numbers cross.

use std::fmt::Write as _;
use std::path::Path;

fn floats(v: &toml::Value, table: &str, key: &str) -> Vec<f64> {
    v[table][key]
        .as_array()
        .unwrap_or_else(|| panic!("{table}.{key} missing"))
        .iter()
        .map(|x| {
            x.as_float()
                .or_else(|| x.as_integer().map(|i| i as f64))
                .unwrap()
        })
        .collect()
}

fn float(v: &toml::Value, table: &str, key: &str) -> f64 {
    v[table][key]
        .as_float()
        .or_else(|| v[table][key].as_integer().map(|i| i as f64))
        .unwrap_or_else(|| panic!("{table}.{key} missing"))
}

fn arr(out: &mut String, name: &str, vals: &[f64]) {
    write!(out, "pub const {name}: [f32; {}] = [", vals.len()).unwrap();
    for v in vals {
        write!(out, "{:?}f32, ", *v as f32).unwrap();
    }
    out.push_str("];\n");
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let path = Path::new(&manifest).join("../../data/nes-levels.toml");
    println!("cargo:rerun-if-changed={}", path.display());
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let v: toml::Value = text.parse().unwrap();

    let mut out = String::from(
        "// Generated by build.rs from data/nes-levels.toml. Do not edit.\n",
    );
    for (name, key) in [
        ("LOW", "low_volts"),
        ("HIGH", "high_volts"),
        ("LOW_ATTENUATED", "low_attenuated_volts"),
        ("HIGH_ATTENUATED", "high_attenuated_volts"),
    ] {
        arr(&mut out, name, &floats(&v, "levels", key));
    }
    for (name, key) in [
        ("SYNC", "sync_volts"),
        ("BURST_LOW", "burst_low_volts"),
        ("BURST_HIGH", "burst_high_volts"),
    ] {
        writeln!(out, "pub const {name}: f32 = {:?}f32;", float(&v, "levels", key) as f32).unwrap();
    }
    // Blanking equals black: the page states blanking sits at the $0F level
    // and $xE/$xF output the same voltage as $1D, i.e. LOW[1].
    out.push_str("pub const BLANK: f32 = LOW[1];\n");
    // Emphasis bit -> attenuated wave, in u3 bit order (bit 0 = PPUMASK
    // bit 5, bit 1 = bit 6, bit 2 = bit 7), per the nesdev tint table.
    writeln!(
        out,
        "pub const EMPHASIS_WAVES: [u8; 3] = [{}, {}, {}];",
        float(&v, "phase", "emphasis_bit5_wave") as u8,
        float(&v, "phase", "emphasis_bit6_wave") as u8,
        float(&v, "phase", "emphasis_bit7_wave") as u8,
    )
    .unwrap();
    writeln!(
        out,
        "pub const COLORBURST_WAVE: u8 = {};",
        float(&v, "phase", "colorburst_wave") as u8
    )
    .unwrap();

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("levels.rs");
    std::fs::write(dest, out).unwrap();
}
