//! Emits the ST 170M constants (data/broadcast-timing.toml), the base
//! matrix (data/yuv-matrix.toml) and the encoder chroma lowpass
//! (data/filters/rgb-encoder.toml) as Rust. Numbers cross here only.

use std::fmt::Write as _;
use std::path::Path;

fn load(manifest: &str, rel: &str) -> toml::Value {
    let path = Path::new(manifest).join(rel);
    println!("cargo:rerun-if-changed={}", path.display());
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()))
        .parse()
        .unwrap()
}

fn f(v: &toml::Value, table: &str, key: &str) -> f64 {
    v[table][key]
        .as_float()
        .or_else(|| v[table][key].as_integer().map(|i| i as f64))
        .unwrap_or_else(|| panic!("{table}.{key} missing"))
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let bt = load(&manifest, "../../data/broadcast-timing.toml");
    let mx = load(&manifest, "../../data/yuv-matrix.toml");
    let flt = load(&manifest, "../../data/filters/rgb-encoder.toml");

    let mut out = String::from("// Generated by build.rs. Do not edit.\n");
    for (name, table, key) in [
        ("WHITE_IRE", "levels_ire", "white"),
        ("BLACK_IRE", "levels_ire", "black_setup"),
        ("BLANK_IRE", "levels_ire", "blanking"),
        ("BURST_PP_IRE", "levels_ire", "burst_pp"),
        ("SYNC_IRE", "levels_ire", "sync"),
        ("IRE_PER_VOLT", "levels_ire", "ire_per_volt"),
        ("LINE_US", "horizontal", "line_us"),
        ("BLANKING_TO_HREF_US", "horizontal", "blanking_start_to_href_us"),
        ("SYNC_US", "horizontal", "sync_us"),
        ("HREF_TO_BLANKING_END_US", "horizontal", "href_to_blanking_end_us"),
        ("Y_SCALE", "encoding", "y_scale"),
        ("SETUP_IRE", "encoding", "setup_ire"),
        ("U_SCALE", "encoding", "u_scale"),
        ("V_SCALE", "encoding", "v_scale"),
        ("CAMERA_GAIN", "camera", "gain"),
        ("CAMERA_POWER", "camera", "power"),
        ("CAMERA_OFFSET", "camera", "offset"),
        ("CAMERA_LINEAR_SLOPE", "camera", "linear_slope"),
        ("CAMERA_LINEAR_BELOW", "camera", "linear_below"),
    ] {
        writeln!(out, "pub const {name}: f32 = {:?}f32;", f(&bt, table, key) as f32).unwrap();
    }
    for (name, key) in [
        ("BURST_START_CYCLES", "href_to_burst_start_cycles"),
        ("BURST_CYCLES", "burst_cycles"),
        ("BURST_FREE_LINES_PER_FIELD", "burst_free_vertical_lines_per_field"),
    ] {
        writeln!(
            out,
            "pub const {name}: usize = {};",
            f(&bt, "horizontal", key) as usize
        )
        .unwrap();
    }
    for (name, key) in [("BASE_Y", "y"), ("BASE_BMY", "b_minus_y"), ("BASE_RMY", "r_minus_y")] {
        let row: Vec<f64> = mx["base"][key]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_float().unwrap())
            .collect();
        write!(out, "pub const {name}: [f32; 3] = [").unwrap();
        for v in &row {
            write!(out, "{:?}f32, ", *v as f32).unwrap();
        }
        out.push_str("];\n");
    }
    let taps: Vec<f64> = flt["chroma_lowpass"]["taps"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_float().unwrap())
        .collect();
    write!(out, "pub const CHROMA_LOWPASS: [f32; {}] = [", taps.len()).unwrap();
    for t in &taps {
        write!(out, "{:?}f32, ", *t as f32).unwrap();
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("st170.rs");
    std::fs::write(dest, out).unwrap();
}
