//! Emits the Rung A filter taps (data/filters/rung-a.toml, generated by
//! tools/gen-filters.py) and the inverse matrix (data/yuv-matrix.toml, the
//! transcription) as Rust constants. Numbers cross here and nowhere else.

use std::fmt::Write as _;
use std::path::Path;

fn float(v: &toml::Value, table: &str, key: &str) -> f64 {
    v[table][key]
        .as_float()
        .or_else(|| v[table][key].as_integer().map(|i| i as f64))
        .unwrap_or_else(|| panic!("{table}.{key} missing"))
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let filters_path = Path::new(&manifest).join("../../data/filters/rung-a.toml");
    let matrix_path = Path::new(&manifest).join("../../data/yuv-matrix.toml");
    println!("cargo:rerun-if-changed={}", filters_path.display());
    println!("cargo:rerun-if-changed={}", matrix_path.display());

    let filters: toml::Value = std::fs::read_to_string(&filters_path)
        .unwrap_or_else(|e| {
            panic!(
                "{}: {e}\nrun tools/gen-filters.py first",
                filters_path.display()
            )
        })
        .parse()
        .unwrap();
    let matrix: toml::Value = std::fs::read_to_string(&matrix_path)
        .unwrap()
        .parse()
        .unwrap();

    let mut out = String::from("// Generated by build.rs. Do not edit.\n");
    for (name, table) in [("CHROMA_BANDPASS", "chroma_bandpass"), ("UV_LOWPASS", "uv_lowpass")] {
        let taps: Vec<f64> = filters[table]["taps"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_float().unwrap())
            .collect();
        write!(out, "pub const {name}: [f32; {}] = [", taps.len()).unwrap();
        for t in &taps {
            write!(out, "{:?}f32, ", *t as f32).unwrap();
        }
        out.push_str("];\n");
    }
    writeln!(
        out,
        "pub const CHROMA_GAIN_AT_SUBCARRIER: f32 = {:?}f32;",
        float(&filters, "chroma_bandpass", "gain_at_subcarrier") as f32
    )
    .unwrap();
    for (name, key) in [
        ("R_FROM_V", "r_from_v"),
        ("G_FROM_U", "g_from_u"),
        ("G_FROM_V", "g_from_v"),
        ("B_FROM_U", "b_from_u"),
    ] {
        writeln!(out, "pub const {name}: f32 = {:?}f32;", float(&matrix, "inverse", key) as f32).unwrap();
    }
    writeln!(
        out,
        "pub const CHROMA_SAT_CORRECTION: f32 = {:?}f32;",
        float(&matrix, "saturation", "chroma_correction")
    )
    .unwrap();

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("tables.rs");
    std::fs::write(dest, out).unwrap();
}
