#!/usr/bin/env python3
"""Generates data/filters/rung-a.toml: the Rung A FIR taps, with every
design parameter recorded in the output header (handoff spec section 5:
hand-tuned taps are not accepted).

Design, all authored and stated here:
- Chroma bandpass: difference of two Hamming-windowed sincs around f_sc,
  half-width 1.0 MHz, 51 taps. Luma is the exact complement (input minus
  extracted chroma), so one kernel serves both and the split is
  delay-matched by symmetry.
- Post-demodulation U/V lowpass: Hamming-windowed sinc, 0.6 MHz cutoff,
  101 taps (an equiband receiver; the page notes real receivers decode
  YUV, not split-bandwidth YIQ).

The script also measures the bandpass's actual gain at f_sc by DFT and
records it, so the decoder normalizes by a measured number rather than an
assumed 1.0.
"""
import math
from datetime import date
from fractions import Fraction
from pathlib import Path

FSC = Fraction(315_000_000, 88)  # Hz, exact
FS = 12 * FSC
CHROMA_HALF_WIDTH_HZ = 1_000_000
CHROMA_TAPS = 51
UV_CUTOFF_HZ = 600_000
UV_TAPS = 101


def lowpass(fc, n):
    """Hamming-windowed sinc, cutoff fc in cycles/sample, DC gain 1."""
    m = n // 2
    taps = []
    for i in range(n):
        x = i - m
        h = 2 * fc if x == 0 else math.sin(2 * math.pi * fc * x) / (math.pi * x)
        w = 0.54 - 0.46 * math.cos(2 * math.pi * i / (n - 1))
        taps.append(h * w)
    s = sum(taps)
    return [t / s for t in taps]


def gain_at(taps, f):
    """SIGNED response at f cycles/sample, evaluated in zero-phase form
    (taps centered). A symmetric FIR's response is real, and its sign is
    part of the answer: the first version of this function returned a
    magnitude, which hid a bandpass built as narrow-minus-wide (passband
    gain -0.907) until the decoder's hue ladder came out 180 degrees
    rotated. Measured, then fixed; the sign stays recorded."""
    m = len(taps) // 2
    return sum(t * math.cos(2 * math.pi * f * (i - m)) for i, t in enumerate(taps))


def main():
    fs = float(FS)
    fsc = float(FSC)
    lo = lowpass((fsc - CHROMA_HALF_WIDTH_HZ) / fs, CHROMA_TAPS)
    hi = lowpass((fsc + CHROMA_HALF_WIDTH_HZ) / fs, CHROMA_TAPS)
    # Wide lowpass minus narrow: positive passband gain at f_sc.
    chroma = [b - a for a, b in zip(lo, hi)]
    chroma_gain = gain_at(chroma, fsc / fs)
    uv = lowpass(UV_CUTOFF_HZ / fs, UV_TAPS)

    out = Path(__file__).resolve().parent.parent / "data/filters/rung-a.toml"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write("# Generated by tools/gen-filters.py. Do not edit by hand;\n")
        f.write("# regenerate and rerun the decode tests instead.\n\n")
        f.write("[provenance]\n")
        f.write('generator = "tools/gen-filters.py"\n')
        f.write(f'generated = "{date.today().isoformat()}"\n')
        f.write('design = "Hamming-windowed sinc; chroma bandpass as difference of two lowpasses; luma is the exact complement in the decoder"\n')
        f.write(f"sample_rate_hz = \"{FS.numerator}/{FS.denominator}\"\n")
        f.write(f"subcarrier_hz = \"{FSC.numerator}/{FSC.denominator}\"\n")
        f.write(f"chroma_half_width_hz = {CHROMA_HALF_WIDTH_HZ}\n")
        f.write(f"uv_cutoff_hz = {UV_CUTOFF_HZ}\n\n")
        f.write("[chroma_bandpass]\n")
        f.write(f"taps = [{', '.join(f'{t:.10e}' for t in chroma)}]\n")
        f.write(f"gain_at_subcarrier = {chroma_gain:.10f}  # measured by DFT, used for normalization\n\n")
        f.write("[uv_lowpass]\n")
        f.write(f"taps = [{', '.join(f'{t:.10e}' for t in uv)}]\n")
    print(f"wrote {out}: chroma {CHROMA_TAPS} taps (gain at f_sc {chroma_gain:.4f}), uv {UV_TAPS} taps")


if __name__ == "__main__":
    main()
